FROM python:3.8.10

RUN python -m pip install --upgrade pip

# add files 
COPY . /Dummy-Project
WORKDIR /Dummy-Project

# install requirements 
RUN pip install -r core/requirements.txt

EXPOSE 8000