version: '3.8'

services:

  dummy_project:
    container_name: dummy-project
    image: chongjingting/dummy-project:0.0.2
    environment:
      NUM_GUNICORN_WORKERS: ${NUM_GUNICORN_WORKERS}
    ports:
      - "8000:8000"
    networks:
      - "dummy_network"
    entrypoint: bash -c "./service_provider/api/gunicorn.sh"

  dummy_db:
    container_name: dummy-db
    image: postgres
    ports:
      - "8001:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data/01_postgres:/docker-entrypoint-initdb.d
    networks:
      - "dummy_network"
    command: ["postgres", "-c", "max_connections=10000"]

networks:
  dummy_network:
      driver: bridge
      name: dummy-network
